version: "3.9"

services:
  mysql_db:
    container_name: go_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yw2qq7tf
      MYSQL_USER: master
      MYSQL_PASSWORD: yw2qq7tf
      MYSQL_DATABASE: trabgb
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: {}