basePath: /
host: localhost:8000
info:
  contact:
    email: suporte@exemplo.com
    name: Suporte da API
    url: http://www.exemplo.com/suporte
  description: Esta é a API para gerenciamento de usuários e tarefas.
  license:
    name: Licença Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API de Usuários e Tarefas
  version: "1.0"
paths: {}
swagger: "2.0"
